# Generated by Django 3.1 on 2020-08-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('ip', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.BinaryField()),
                ('mime', models.CharField(max_length=25)),
                ('filename', models.CharField(max_length=25)),
            ],
        ),
    ]
